---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
Note: the data for this analysis was downloaded by forking [this GitHub repository](http://github.com/rdpeng/RepData_PeerAssessment1)

```{r packages, results="hide"}
# These libaries are used
library(dplyr)
```


## Loading and preprocessing the data
```{r "loading data"}
if (!file.exists("activity.csv")) {
    unzip("activity.zip")
}
activityData <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
```{r question1}
dailyTotal <- summarise(group_by(activityData, date), steps=sum(steps, na.rm = TRUE))
hist(dailyTotal$steps, breaks=10, xlab="total daily steps", main="Histogram of total daily steps")
summarise(dailyTotal, mean=mean(steps), median=median(steps))
```

## What is the average daily activity pattern?
```{r question2}
intervalAverage <- summarise(group_by(activityData, interval), steps=mean(steps, na.rm = TRUE))
with(intervalAverage, plot(interval, steps, type="l", main="Average number of steps per 5 minute interval accross all days"))
intervalAverage[which.max(intervalAverage$steps), ]
```


## Imputing missing values
```{r question3}
missingValueCount <- nrow(activityData[is.na(activityData$steps),])
print(missingValueCount)

# fill in the missing values with the average value of the same interval
activityData$steps2 <- activityData$steps
blankRows <- is.na(activityData$steps)
matchingInterval <- match(activityData$interval[blankRows], intervalAverage$interval)
activityData$steps2[blankRows] <- intervalAverage$steps[matchingInterval]
activityData2 <- select(activityData, steps=steps2, date, interval)
dailyTotal2 <- summarise(group_by(activityData2, date), steps=sum(steps))
hist(dailyTotal2$steps, breaks=10, xlab="total daily steps", main="Histogram of total daily steps (NA's replaced with interval average)")

# Mean and Media ignoring NA's
summary1 <- summarise(dailyTotal, mean=mean(steps), median=median(steps))
print (summary1)

# Mean and median with NA's replaced
summary2 <- summarise(dailyTotal2, mean=mean(steps), median=median(steps))
print (summary2)

# What is the impact (in percent)?
(summary2-summary1)/summary2*100
```



## Are there differences in activity patterns between weekdays and weekends?
